#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
( cd "$SCRIPTDIR" || exit 1 )

( export PYTHONPATH="$SCRIPTDIR/..:$SCRIPTDIR/../markup:$PYTHONPATH" && . "$SCRIPTDIR/../venv/bin/activate" && python3 "$SCRIPTDIR/../markup/xml2distance.py" "$1" "$2" )

